task 9 part 3 periodicAgentUpdate()
ilanshamir/connect-scripts pull request #7
Opened 2020-07-25 18:08 UTC by jack-am

Made function that updates the list of agents every 30 seconds, and sends an alert that tells the user if there is no new agents or a list of the new agent IDs

2020-07-25 22:33 UTC, emmashamir commented on Resilio Connect API/JSMonitor/app.js
> +    if (findArrayDiff(updatedList, prevList).length != 0) {
This won't work because you made update list equal to prev list so there isn't gonna be any difference between this

2020-07-27 01:35 UTC, ilanshamir requested changes

2020-07-27 01:35 UTC, ilanshamir commented on Resilio Connect API/JSMonitor/app.js
> +        console.log("ALERT: " + findArrayDiff(updatedList, prevList));
It is better not to call the same function twice.  It is a waste fo cpu time.
Call it once and use the result when you need it.

2020-07-27 01:35 UTC, ilanshamir commented on Resilio Connect API/JSMonitor/app.js
> +    setTimeout(function() {periodicAgentUpdate();}, 30000);
It is better to make the time delay (e.g., 30000) a parameter

2020-07-27 01:35 UTC, ilanshamir commented on Resilio Connect API/JSMonitor/app.js
> +function periodicAgentUpdate() {
Structure-wise, I would like to separate the calculation of the diff from the action that should be taken when there is a diff.  So the function periodicAgentUpdate() should take a callback function as a parameter and call it when a diff is detected.  Let me know if you need help with this one.

2020-07-27 01:35 UTC, ilanshamir commented on Resilio Connect API/JSMonitor/app.js
> +var updatedList = [];
What would happen the first time periodicAgentUpdate() is called?  Will it detect new Agents? Are they actually new?

2020-07-30 01:22 UTC, ilanshamir requested changes

2020-07-30 01:22 UTC, ilanshamir commented on Resilio Connect API/JSMonitor/app.js
> +var callCounter = 0;
these 2 variables belong inside the class.  otherwise, you are still using global variables that we want to avoid.

2020-07-30 01:22 UTC, ilanshamir commented on Resilio Connect API/JSMonitor/app.js
> +        console.log("ALERT: The new agents this cycle are " + diffArray);
The callback function should not use "callCounter" which is an internal variable.  It should use the value that is passed to it which is the diffArray.

2020-07-30 01:22 UTC, ilanshamir commented on Resilio Connect API/JSMonitor/app.js
> +    periodicUpdate(freq, ifDifferent) {
The code would be more readable if "ifDifferent" is renamed to "onDifferentCallback"

2020-08-02 00:50 UTC, merged